### PR TITLE
fix inclusion of rnnoise.h into C++ code

### LINKED ISSUE #120: Include headers missing extern C
The include headers don't have an `extern "C"` directive, which makes it harder to #include from a c++ application. Can you add `extern "C"` to rnnoise.h?

### PR DESCRIPTION
**Pull request by j-schultz**
FIxes #120

### CODE REVIEW

**Comment by winstondu** [comment]
@jmvalin , this is very much needed! Please approve!

**Comment by petterreinholdtsen** [comment]
This change partly conflicts with the changes in pull request #88.

**Comment by j-schultz** [comment]
The changes to rnnoise.h could be dropped in #88 for a cleaner separation of PRs, or #88 could be merged as-is and #131 could be closed instead. It doesn't really matter to me.

**Comment by petterreinholdtsen** [comment]
I take the chance and merge this one, which will invalidate #88 until it is rebased.

**Pull request merged**
